# Generated by Django 3.2.9 on 2022-03-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='topic',
            new_name='content',
        ),
    ]
